import React from 'react'
import Navbar from '../componentes/Navbar'
import '../estilos.css/Politica.css'
import imgL from '../assets/imagenes/search.png'

const Politica = () => {
  return (
    <div>
      <Navbar />
      <h1>Politica</h1>
    <div className='containerSe'>  
      <div className='contenedorTer'> 
        <p className='titulos'>Términos de uso y política de privacidad</p>
         
          <div className='contenedorInput2'>  
             <div className='input2'>  
              <input type="text" placeholder='buscar'/>
              <img src={imgL} alt="imagenBuscador" height='23px'/>
             </div> 
          </div> 


       </div>  
      <p className='titulos2'>Términos de uso y política de privacidad</p>
      <p className='titulos3'>Última modificación realizada el 26 de julio de 2019</p>
      <p className='titulos4'>Aceptación de estos términos</p>
      <p className='titulos3'>Al utilizar la aplicación móvil de ScripturePlus en dispositivos iOS o Android, ya sea como usuario registrado o no registrado, usted acepta y está de acuerdo con estos Términos. Por favor, lea atentamente estos Términos y la Política de Privacidad antes de utilizar ScripturePlus. Si no está de acuerdo con estos Términos o con la Política de Privacidad, no debe utilizar ni acceder a ScripturePlus.</p>  
      <p className='titulos4'>Cambios en los Términos</p>
      <p className='titulos3'>ScripturePlus es producto de Book of Mormon Central, propiedad de Book of Mormon Archaeological Forum, Inc. Es posible que revisemos y actualicemos estos Términos de vez en cuando a nuestra entera discreción.  Cualquier cambio es efectivo tan pronto como lo publiquemos. El uso continuo de ScripturePlus después de la publicación de los Términos revisados significa que usted acepta y está de acuerdo con los cambios.</p>
      <p className='titulos4'>Cambios en ScripturePlus</p>
      <p className='titulos3'>Esperamos ofrecer ScripturePlus y todas sus características a perpetuidad, pero nos reservamos el derecho de cambiar o dejar de ofrecer ScripturePlus o cualquier parte, porción o función dentro de ScripturePlus en cualquier momento sin previo aviso. No seremos responsables si por cualquier razón todo o parte de ScripturePlus no está disponible en cualquier momento.</p>
      <p className='titulos4'>Información sobre usted y su uso de ScripturePlus</p>
      <p className='titulos3'>Toda la información que recopilamos en o a través de ScripturePlus está sujeta a nuestra Política de Privacidad. Al utilizar ScripturePlus, usted da su consentimiento a todas las acciones que tomemos con respecto a su información de acuerdo con nuestra Política de Privacidad.</p>
      <p className='titulos4'>Uso permitido y no permitido</p>
      <p className='titulos3'>Los términos abajo le permiten utilizar ScripturePlus de acuerdo con los Términos para su uso personal y no comercial. Todos los derechos no expresamente otorgados a usted están reservados por Book of Mormon Central. Usted acepta que no está autorizado y que no utilizará ScripturePlus como se indica a continuación:</p>
      <ul>
        <li>De cualquier manera que viole cualquier ley o regulación federal, estatal, local o internacional; </li>
        <li>Con el propósito de explotar, dañar o intentar explotar o dañar a menores de edad de cualquier manera, exponiéndolos a contenido inapropiado o solicitándoles información personal identificable;</li>
        <li>Suplantar o intentar suplantar a cualquier compañía o persona, incluyendo a Book of Mormon Central u otro usuario de ScripturePlus;</li>
        <li>Participar en cualquier otra conducta que, según lo determinado por nosotros, pueda dañar a Book of Mormon Central o a los usuarios de ScripturePlus o exponerlos a responsabilidad;</li>
        <li>De cualquier manera que pueda deshabilitar, sobrecargar, dañar o deteriorar ScripturePlus o interferir con el uso de ScripturePlus por parte de otros;</li>
        <li>Utilizar cualquier robot, araña u otro dispositivo, proceso o medio automático para acceder a ScripturePlus con cualquier propósito, incluyendo el monitoreo o la copia de cualquier material de ScripturePlus;</li>
        <li>Introducir virus, troyanos, gusanos, bombas lógicas u otro material malicioso o tecnológicamente dañino;</li>
        <li>Intentar obtener acceso no autorizado a, interferir con, dañar o interrumpir cualquier parte de ScripturePlus o cualquier servidor, computadora o base de datos conectada a ScripturePlus;</li>
        <li>Para descompilar o intentar realizar ingeniería inversa en el código fuente de ScripturePlus;</li>
        <li>Atacar ScripturePlus mediante un ataque de denegación de servicio o un ataque de denegación de servicio distribuido;</li>
        <li>Intentar interferir con el funcionamiento adecuado de ScripturePlus.</li>
      </ul>
      <p className='titulos3'>Usted también acepta que no enviará, a sabiendas recibirá, cargará, descargará, usará o reutilizará ningún material que, según lo determine Book of Mormon Central a su entera discreción:</p>
      <ul>
        <li>Contiene cualquier material que sea difamatorio, obsceno, indecente, abusivo, ofensivo, acosador, violento, odioso, provocativo o de cualquier otra manera objetable;</li>
        <li>Promueve material sexualmente explícito o pornográfico, violencia o discriminación por cualquier motivo, incluyendo el basado en raza, sexo, religión, nacionalidad, discapacidad, orientación sexual o edad;</li>
        <li>Infringe cualquier patente, marca registrada, secreto comercial, derechos de autor, derechos de propiedad intelectual u otros derechos de cualquier otra persona;</li>
        <li>Viola los derechos legales (incluyendo los derechos de publicidad y privacidad) de otros o contiene cualquier material que pueda dar lugar a cualquier responsabilidad civil o penal bajo las leyes o regulaciones aplicables;</li>
        <i>Promueve cualquier actividad ilegal, o aboga, promueve o ayuda en cualquier acto ilegal;</i>
        <li>Involucra actividad comercial o ventas, tales como concursos, sorteos y otras promociones de ventas, trueque o publicidad;</li>
        <li>Da la impresión de que el material emana de o está endosado por Book of Mormon Central o cualquier otra persona o entidad, si este no es el caso.</li>
         </ul>
         <p className='titulos4'>Aportaciones de los usuarios</p>
      <p className='titulos3'>Cuando ScripturePlus permite a los usuarios publicar, enviar, publicar, mostrar o transmitir a otros usuarios u otras personas contenido o materiales, todas las contribuciones de los usuarios deben cumplir con estos Términos. Podemos o no revisar las contribuciones de los usuarios o cualquier otro material antes de que se publique y no podemos garantizar la eliminación inmediata de material objetable después de que se haya publicado. Por lo tanto, no asumimos ninguna responsabilidad por cualquier acción u omisión en relación con las transmisiones, comunicaciones o contenidos proporcionados por cualquier usuario o tercero.</p>
      <p className='titulos3'>Al proporcionar cualquier contribución del usuario en o a través de ScripturePlus, usted nos concede a nosotros y a nuestros proveedores de servicios, y a cada uno de ellos y a nuestros respectivos licenciatarios, sucesores y cesionarios, el derecho de usar, reproducir, modificar, ejecutar, mostrar, distribuir o de otra manera revelar a terceros dicho material. Usted declara y garantiza que posee o controla todos los derechos sobre las aportaciones de usuario y que tiene el derecho de conceder esta licencia para que todas sus contribuciones de usuario cumplan y cumplirán con estos Términos. No somos responsables del contenido ni de la exactitud de las contribuciones de los usuarios publicadas por usted o por cualquier otro usuario de ScripturePlus.</p>
      <p className='titulos4'>Seguridad de acceso</p>
      <p className='titulos3'>ScripturePlus permite a los usuarios registrarse, lo que requiere proporcionar cierta información a ScripturePlus.  Usted acepta que toda la información que proporcione para convertirse en un usuario registrado de ScripturePlus, incluyendo, pero no limitado a, la información proporcionada a través del uso de cualquier característica interactiva en ScripturePlus, se rige por nuestra Política de Privacidad y usted consiente en todas las acciones que tomemos con respecto a su información de acuerdo con nuestra Política de Privacidad.</p>
      <p className='titulos3'>Si usted elige o se le proporciona un nombre de usuario, contraseña o información similar como parte de nuestros procedimientos de seguridad, usted acepta tratar dicha información como confidencial, y acepta notificarnos inmediatamente de cualquier acceso o uso no autorizado de su nombre de usuario o contraseña o cualquier otra violación de la seguridad. Tenemos el derecho de desactivar cualquier nombre de usuario, contraseña u otro identificador, ya sea elegido por usted o proporcionado por nosotros, en cualquier momento si, en nuestra opinión, el usuario ha violado alguna disposición de estos Términos.</p>
      <p className='titulos4'>Monitoreo y Aplicación; Cumplimiento Legal; Rescisión</p>
      <p className='titulos3'>Usted está de acuerdo en que tenemos derecho a:</p>
      <ul>
        <li>Tomar cualquier acción con respecto a cualquier usuario, usuario registrado o contribución de usuario que consideremos necesaria o apropiada a nuestra discreción si creemos que hay una violación de estos Términos, violación de los derechos de terceros, una amenaza a la seguridad personal de otros, o una amenaza o responsabilidad o daño a la buena voluntad asociada con ScripturePlus o Book of Mormon Central. </li>
        <li>Tomar las medidas apropiadas, incluyendo, sin limitación, referencia a la aplicación de la ley y la divulgación de su información, para cualquier uso ilegal o no autorizado de ScripturePlus;</li>
        <li>Terminar o suspender su acceso a todo o parte de ScripturePlus por cualquier o ninguna razón, incluyendo sin limitación, cualquier violación de estos Términos.</li>
      </ul>
      <p className='titulos3'>Sin perjuicio de lo anterior, tenemos derecho a cooperar plenamente con las autoridades encargadas de hacer cumplir la ley o con una orden judicial que nos solicite u ordene revelar la identidad u otra información de cualquier persona que publique cualquier material en o a través de ScripturePlus.
         USTED RENUNCIA Y MANTIENE INDEMNE A BOOK OF MORMON CENTRAL Y SUS LICENCIATARIOS Y PROVEEDORES DE SERVICIOS Y A TODOS SUS TRABAJADORES, OFICIALES Y DIRECTORES DE CUALQUIER RECLAMO QUE RESULTE DE CUALQUIER ACCIÓN TOMADA POR Y DE LAS PARTES MENCIONADAS ANTERIORMENTE DURANTE O COMO RESULTADO DE INVESTIGACIONES LEGALES Y DE CUALQUIER ACCIÓN TOMADA COMO CONSECUENCIA DE INVESTIGACIONES REALIZADAS POR BOOK OF MORMON CENTRAL O POR LAS AUTORIDADES DE APLICACIÓN DE LA LEY.</p>
      <p className='titulos4'>Su confianza en la información y las traducciones</p>
      <p className='titulos3'>La información presentada en o a través de ScripturePlus está disponible únicamente para propósitos de información general. No garantizamos la exactitud, integridad o utilidad de esta información. Nos esforzamos por ser precisos, pero cualquier confianza que usted deposite en dicha información es estrictamente bajo su propio riesgo. El material traducido a otros idiomas pasa por varios niveles de revisión de control de calidad, pero no garantizamos la exactitud de esas traducciones. Rechazamos toda responsabilidad que surja de la confianza depositada en dichos materiales por usted o por cualquier otro usuario de ScripturePlus.</p>
      <p className='titulos4'>Derechos de propiedad intelectual</p>
      <p className='titulos3'>ScripturePlus y su contenido, características y funcionalidad (incluyendo pero no limitado a toda la información, software, texto, pantallas, imágenes, video, audio y el diseño, selección y disposición de los mismos), son propiedad de Book of Mormon Central, sus licenciatarios u otros proveedores de dicho material y están protegidos por las leyes de derechos de autor, marcas registradas, patentes, secretos de marca y otras leyes de propiedad intelectual o derechos de propiedad de Estados Unidos e internacionales.</p>
      <p className='titulos4'>Logotipos y diseños</p>
      <p className='titulos3'>El nombre de ScripturePlus, el nombre y el logotipo de Book of Mormon Central, todos los nombres relacionados, logotipos, nombres de productos y servicios, diseños y eslóganes o lema son marcas registradas y/o derechos de autor de Book of Mormon Central. Usted no debe usar estas marcas y derechos de autor sin el permiso previo por escrito de Book of Mormon Central. Todos los demás nombres, logotipos, nombres de productos y servicios, diseños y eslóganes de ScripturePlus son marcas comerciales y/o derechos de autor de sus respectivos propietarios.</p>
      <p className='titulos4'>Infracción de la propiedad intelectual</p>
      <p className='titulos3'>Si usted cree que cualquier contenido de ScripturePlus, incluyendo las contribuciones de los usuarios, infringe sus derechos de propiedad intelectual, incluyendo los derechos de autor, por favor envíenos una notificación de la infracción de derechos de autor a través del formulario de contacto https://bookofmormoncentral.es/contact. Tenga en cuenta que la política de Book of Mormon Central es terminar el acceso de usuarios infractores reincidentes.</p>
      <p className='titulos4'>Enlaces y servicios de terceros</p>
      <p className='titulos3'>ScripturePlus puede incluir contenido proporcionado por terceros. Si ScripturePlus contiene enlaces a otros sitios o recursos proporcionados por terceros, dichos enlaces y recursos se proporcionan únicamente para su conveniencia.  No tenemos control sobre el contenido de esos sitios o recursos y no aceptamos ninguna responsabilidad por ellos ni por cualquier pérdida o daño que pueda surgir del uso de ellos. Si usted decide acceder a cualquiera de los sitios web de terceros enlazados desde ScripturePlus, lo hace bajo su propio riesgo y sujeto a los términos y condiciones de uso de dichos sitios web. Todas las declaraciones y/u opiniones expresadas en estos materiales, todos los artículos y respuestas a preguntas y otros contenidos, aparte del contenido proporcionado por Book of Mormon Central, son únicamente las opiniones y es responsabilidad de la persona o entidad que proporciona esos materiales. Estos materiales no necesariamente reflejan la opinión de Book of Mormon Central. No somos responsables, ante usted ni ante terceros, del contenido ni de la exactitud de los materiales proporcionados por terceros.</p>
      <p className='titulos4'>Enlaces desde y hacia ScripturePlus y las plataformas de medios sociales</p>
      <p className='titulos3'>ScripturePlus puede proporcionar ciertas características que le permiten conectarse o enlazarse a o desde los medios sociales, así como a otros sitios web y aplicaciones de terceros, y compartir información y comunicaciones con y desde ScripturePlus y dichos servicios de terceros. Usted puede utilizar estas funciones únicamente en la medida en que son proporcionadas por nosotros solo con respecto al contenido con el que se muestran y de otro modo de acuerdo con estos Términos y cualquier otra condición y término adicional que proporcionemos con respecto a dichas funciones. Podemos desactivar cualquiera o todas estas funciones en cualquier momento sin previo aviso a nuestra entera discreción.</p>
      <p className='titulos4'>Restricciones geográficas</p>
      <p className='titulos3'>Book of Mormon Central, el propietario de ScripturePlus, tiene su sede en el estado de Utah en los Estados Unidos. No afirmamos que ScripturePlus o cualquiera de sus contenidos sea accesible o apropiado fuera de los Estados Unidos. El acceso a ScripturePlus puede no ser legal para ciertas personas o en ciertos países. Si usted accede a ScripturePlus desde fuera de los Estados Unidos, lo hace por su propia iniciativa y es responsable del cumplimiento de las leyes locales.</p>
      <p className='titulos4'>Exclusión de garantías</p>
      <p  className='titulos3'>EL USO QUE USTED DE A SCRIPTUREPLUS, SU CONTENIDO Y CUALQUIER FUNCIONALIDAD, SERVICIO O ELEMENTO OBTENIDO A TRAVÉS DE SCRIPTUREPLUS ES BAJO SU PROPIO RIESGO. TODOS SE PROPORCIONAN "TAL CUAL" Y "SEGÚN DISPONIBILIDAD", SIN GARANTÍAS DE NINGÚN TIPO, YA SEAN EXPRESAS O IMPLÍCITAS. NI BOOK OF MORMON CENTRAL NI NINGUNA PERSONA ASOCIADA CON BOOK OF MORMON CENTRAL OFRECE NINGUNA GARANTÍA O REPRESENTACIÓN CON RESPECTO A LA INTEGRIDAD, SEGURIDAD, CONFIABILIDAD, CALIDAD, EXACTITUD O DISPONIBILIDAD DE SCRIPTUREPLUS. SIN LIMITAR LO ANTERIOR, NI BOOK OF MORMON CENTRAL NI NADIE ASOCIADO CON BOOK OF MORMON CENTRAL REPRESENTA O GARANTIZA QUE SCRIPTUREPLUS O CUALQUIER CONTENIDO FUNCIONAL O CUALQUIER SERVICIO O ELEMENTO OBTENIDO A TRAVÉS DE SCRIPTUREPLUS SERÁ PRECISO, CONFIABLE, LIBRE DE ERRORES O SIN INTERRUPCIONES, QUE LOS DEFECTOS SERÁN CORREGIDOS, QUE SCRIPTUREPLUS O EL SERVIDOR QUE LO HACE DISPONIBLE ESTÁN LIBRES DE VIRUS U OTRO CONTENIDO DAÑINO, O QUE SCRIPTUREPLUS O CUALQUIER SERVICIO O ARTÍCULO OBTENIDO A TRAVÉS DE SCRIPTUREPLUS DE OTRA MANERA SATISFARÁ SUS NECESIDADES O EXPECTATIVAS.

       BOOK OF MORMON CENTRAL POR LA PRESENTE RENUNCIA A TODA GARANTÍA DE CUALQUIER TIPO, YA SEA EXPRESA O IMPLÍCITA, ESTATUTARIA O DE OTRO TIPO, INCLUYENDO, PERO NO LIMITADO A CUALQUIER GARANTÍA DE COMERCIABILIDAD, NO INFRACCIÓN Y ADECUACIÓN PARA CUALQUIER PROPÓSITO EN PARTICULAR.

       LO ANTERIOR NO AFECTA NINGUNA GARANTÍA QUE NO PUEDA SER EXCLUIDA O LIMITADA BAJO LA LEY APLICABLE.</p>
      <p className='titulos4'>Limitación de responsabilidad</p>
      <p className='titulos3' >EN NINGÚN CASO BOOK OF MORMON CENTRAL, SUS LICENCIANTES, PROVEEDORES DE SERVICIOS, O CUALQUIERA DE SUS TRABAJADORES, AGENTES, OFICIALES O DIRECTORES SERÁN RESPONSABLES POR DAÑOS DE NINGÚN TIPO, BAJO NINGUNA TEORÍA LEGAL, QUE SURJAN DE O EN CONEXIÓN CON SU USO, O INCAPACIDAD PARA USAR, SCRIPTUREPLUS, CUALQUIER SITIO WEB VINCULADO A ÉL, CUALQUIER CONTENIDO OFRECIDO EN O A TRAVÉS DE SCRIPUTUREPLUS, U OTROS SITIOS WEB U OTROS SERVICIOS O ARTÍCULOS OBTENIDOS A TRAVÉS DE SCRIPTUREPLUS, INCLUYENDO CUALQUIER DAÑO DIRECTO, INDIRECTO, ESPECIAL, INCIDENTAL, CONSECUENTE O PUNITIVO, INCLUYENDO PERO NO LIMITADO A LESIONES PERSONALES, DOLOR Y SUFRIMIENTO, ANGUSTIA EMOCIONAL, PÉRDIDA DE INGRESOS, PÉRDIDA DE BENEFICIOS, PÉRDIDA DE NEGOCIO O AHORROS ANTICIPADOS, PÉRDIDA DE USO, PÉRDIDA DE FONDO DE COMERCIO, PÉRDIDA DE DATOS, Y SI ES CAUSADA POR UN AGRAVIO (INCLUYENDO NEGLIGENCIA), INCUMPLIMIENTO DE CONTRATO U OTRO MOTIVO, INCLUSO SI ES PREVISIBLE.</p>
      <p className='titulos3'>LO ANTERIOR NO AFECTA NINGUNA RESPONSABILIDAD QUE NO PUEDA SER EXCLUIDA O LIMITADA BAJO LA LEY APLICABLE.</p>
      <p className='titulos4'>Indemnización</p>
      <p className='titulos3'>Usted acepta defender, indemnizar y eximir de responsabilidad a Book of Mormon Central, sus afiliados, licenciatarios y proveedores de servicios, y a sus respectivos funcionarios, directores, trabajadores, contratistas, agentes, licenciatarios, proveedores, sucesores y cesionarios de y en contra de cualquier reclamo, responsabilidad, daños y perjuicios, sentencias, reconocimientos, pérdidas, costos, gastos u honorarios (incluyendo honorarios razonables de abogados) que surjan de, o estén relacionados con, su violación de estos Términos o su uso de ScripturePlus, incluyendo, pero sin limitarse a, sus contribuciones de usuario, cualquier uso del contenido, servicios y productos de ScripturePlus que no sea expresamente autorizado en estos Términos o el uso por su parte de cualquier información obtenida de ScripturePlus. </p>
      <p className='titulos4'>Ley aplicable y jurisdicción</p>
      <p className='titulos3'>Todos los asuntos, disputas o reclamos relacionados con ScripturePlus y estos Términos (incluyendo disputas o reclamos no contractuales), se regirán e interpretarán de acuerdo con las leyes internas del Estado de Utah sin dar efecto a ninguna disposición o norma de elección o conflicto de leyes. Cualquier demanda legal, acción o procedimiento que surja de o esté relacionado con estos Términos o ScripturePlus se instituirá exclusivamente en los tribunales federales de los Estados Unidos o en los tribunales del Estado de Utah en cada caso ubicado en Salt Lake City. Al aceptar estos Términos y usar ScripturePlus, usted renuncia a cualquier objeción al ejercicio de la jurisdicción sobre usted por parte de dichos tribunales y a la jurisdicción en dichos tribunales.</p>
      <p className='titulos4'>Renuncia y divisibilidad</p>
      <p className='titulos3'>Book of Mormon Central solo puede renunciar a sus derechos bajo estos Términos por escrito. Si una corte u otro tribunal de jurisdicción competente considera que alguna disposición de estos Términos es inválida, ilegal o inaplicable por cualquier razón, dicha disposición se eliminará o limitará en la medida mínima, de modo que las disposiciones restantes de estos Términos continuarán en plena vigencia y efecto.</p>
      <p className='titulos4'>Acuerdo completo</p>
      <p className='titulos3'>Estos Términos y nuestra Política de Privacidad constituyen el único y completo acuerdo entre usted y Book of Mormon Central con respecto a ScripturePlus y reemplazan todos los entendimientos, acuerdos, representaciones y garantías anteriores y contemporáneos, tanto escritos como orales, con respecto a ScripturePlus.</p>
      <p className='titulos4'>Sus comentarios e inquietudes</p>
      <p className='titulos3'>ScripturePlus pertenece y está operado por Book of Mormon Central, propiedad de Book of Mormon Archaeological Forum, Inc, una corporación sin fines de lucro en Utah, con sede administrativa en 553 E 100 N, American Fork, Utah 84003 y operaciones en 330 E 400 S, Springville, Utah 84663.  Todas las opiniones, comentarios, solicitudes de asistencia técnica y otras comunicaciones relacionadas con ScripturePlus deben enviarse por correo electrónico utilizando el formulario de contacto https://bookofmormoncentral.es/contact o por correo a cualquiera de las direcciones mencionadas anteriormente. Cualquier comentario que nos proporciona será considerado no confidencial. Book of Mormon Central será libre de usar tal información sin restricción.</p>
      <p className='titulos4'>ScripturePlus pertenece y está operado por Book of Mormon Central, propiedad de Book of Mormon Archaeological Forum, Inc, una corporación sin fines de lucro en Utah, con sede administrativa en 553 E 100 N, American Fork, Utah 84003 y operaciones en 330 E 400 S, Springville, Utah 84663.  Todas las opiniones, comentarios, solicitudes de asistencia técnica y otras comunicaciones relacionadas con ScripturePlus deben enviarse por correo electrónico utilizando el formulario de contacto https://bookofmormoncentral.es/contact o por correo a cualquiera de las direcciones mencionadas anteriormente. Cualquier comentario que nos proporciona será considerado no confidencial. Book of Mormon Central será libre de usar tal información sin restricción.</p>
      <p className='titulos'>Política de privacidad de ScripturePlus</p>
      <p className='titulos4'>Breve descripción general</p>
      <p className='titulos3'>Esto es lo que encontrará en nuestra Política de Privacidad, que cubre todos los productos y servicios de ScripturePlus.</p>
      <p className='titulos4'>Personalizando su experiencia</p>
      <p className='titulos3'>Cuando usted registra su copia de ScripturePlus o utiliza cualquiera de nuestras aplicaciones o sitios, la información que recopilamos tiene el propósito de ofrecer una experiencia de estudio de las Escrituras más personalizada.</p>
      <p className='titulos4'>Cómo utilizamos sus datos</p>
      <p className='titulos3'>La Política de Privacidad describe los tipos de datos que recopilamos de usted o de su actividad y cómo utilizamos esa información para mejorar su experiencia con ScripturePlus. No compartimos sus datos de identificación personal con ningún anunciante o red publicitaria de terceros.</p>
      <p className='titulos4'>Su privacidad está protegida</p>
      <p className='titulos3'>Las estadísticas que compartimos sobre el compromiso mundial de las Escrituras son compiladas y agregadas de tal manera que su privacidad está protegida. No revelamos su información personal identificable. También implementamos medidas de seguridad estándar de la industria diseñadas para proteger sus datos.</p>
      <p className='titulos4'>La experiencia es suya</p>
      <p className='titulos3'>Nuestra Política de Privacidad delinea sus derechos cuando utiliza ScripturePlus, incluyendo el acceso, el intercambio, el cambio y la eliminación de sus datos personales. También describimos cómo las tecnologías de recolección de datos ayudan a proporcionar funcionalidad y perspicacia para ayudarle a usted a participar más plenamente en ScripturePlus y en las Escrituras.</p>
      <p className='titulos4'>Política de privacidad</p>
      <p className='titulos3'>Última modificación el 26 de julio de 2019.</p>
      <p className='titulos4'>Definiciones</p>
      <p className='titulos3'>ScripturePlus se refiere al código móvil que se ejecuta bajo los sistemas operativos iOS y Android y la API que permite que ese código móvil se comunique con datos basados en servidor. ScripturePlus pertenece y está operado por Book of Mormon Central, propiedad de Book of Mormon Archaeological Forum, Inc. El soporte técnico es proporcionado por Nuvek, LLC. Los usuarios no registrados pueden acceder a funciones limitadas de ScripturePlus. Para acceder a las funciones avanzadas de ScripturePlus, el usuario debe registrarse.</p>
      <p className='titulos4'>Aceptación de los términos</p>
      <p className='titulos3'>Por favor, lea atentamente esta Política de Privacidad, ya que en ella se explica cómo recopilamos, utilizamos, compartimos y procesamos su información personal. Al acceder a ScripturePlus usted acepta esta Política de Privacidad y sus términos y consiente que sus datos sean transferidos y procesados en servidores basados en nube. EL uso que usted dé a ScripturePlus también se rige por nuestros Términos de uso. Por favor, lea estos términos cuidadosamente también.
      Agradecemos cualquier pregunta o comentario que pueda tener sobre esta Política de Privacidad y nuestras prácticas de privacidad. Si tiene alguna pregunta o comentario, puede contactarnos en Book of Mormon Central, 553 E 100 N, American Fork, UT 84003 o por medio del formulario de contacto https://bookofmormoncentral.es/contact</p>
      <p className='titulos4'>Cómo utilizamos su información</p>
      <p className='titulos3'>No compartimos sus datos personales con terceros anunciantes o redes publicitarias para sus fines publicitarios. Utilizamos los 
      datos que recopilamos sobre usted o que usted nos proporciona, incluyendo cualquier información personal, de la siguiente manera:</p>
      <ol>
        <li>Para proporcionarle la funcionalidad avanzada de ScripturePlus y cualquier otra información, productos o servicios que nos solicite;</li>
        <li>Como se describe en esta Política de Privacidad;</li>
        <li>Para cumplir con cualquier otro propósito para el cual usted lo provea;</li>
        <li>Para cumplir con nuestras obligaciones y hacer valer nuestros derechos bajo esta Política de Privacidad y nuestros Términos de Uso;</li>
        <li>De cualquier otra manera podemos describir cuando usted nos proporciona la información;</li>
        <li>Para cualquier otro propósito con su consentimiento.</li>
      </ol>

      <p className='titulos3'>La capacidad que usted tenga para acceder a funciones limitadas dentro de ScripturePlus no depende de que nos proporcione su información personal y usted puede negarse a enviarnos información personal, sin embargo, esto nos prohibirá proporcionarle servicios y funciones avanzadas de ScripturePlus.</p>
      <p className='titulos4'>Facilitando el uso de ScripturePlus</p>
      <p className='titulos3'>Utilizamos sus datos personales para autorizar su acceso a ScripturePlus si usted es un usuario registrado. También utilizamos sus datos personales para habilitar ciertas funciones avanzadas dentro de ScripturePlus. Utilizamos los datos que usted nos provee sobre usted para proporcionar, mejorar y personalizar ScripturePlus utilizando las tecnologías automatizadas discutidas en esta política y las inferencias que hacemos de la información que recopilamos.</p>
      <p className='titulos3'>En algún momento, ScripturePlus puede permitirle comunicarse y conectarse con otros usuarios de ScripturePlus para compartir versículos, mensajes y otros contenidos. La comunicación entre usted y otros puede ocurrir a través de ScripturePlus. Será elección de usted si desea comunicarse o conectarse con otros usuarios de ScripturePlus. Utilizaremos sus datos para facilitar esta comunicación en caso de que usted decida hacerlo. También podemos utilizar la información de contacto de su dispositivo móvil si nos da permiso para acceder a ella.</p>
      <p className='titulos4'>Eventos</p>
      <p className='titulos3'>En algún momento, ScripturePlus puede proporcionarle recomendaciones de geolocalización habilitada para eventos en los que usted puede elegir asistir o participar. Esto requerirá que nos conceda permiso para acceder a los datos de su ubicación</p>
      <p className='titulos4'>Recomendaciones</p>
      <p className='titulos3'>En algún momento, podemos hacer uso de los datos que tenemos sobre usted y de las inferencias que hacemos de esos datos para recomendar contenido que creemos que puede ser de su agrado. Por ejemplo, basado en un plan de lectura que usted complete, ScripturePlus puede recomendarle planes de lectura adicionales que puedan interesarle. Podemos ponernos en contacto con usted a través de notificaciones automatizadas, correos electrónicos o mensajes in-app (que aparezcan dentro de la aplicación) para comunicarle estas recomendaciones, consejos sobre cómo usar ScripturePlus, y otras noticias que se consideren de interés potencial para usted. Tendrá opciones de configuración de suscripción, cancelación de suscripción y notificación para controlar qué mensajes recibe o no.</p>
      <p className='titulos4'>Mensajes relacionados con el servicio</p>
      <p className='titulos3'>Podemos utilizar su información para ponernos en contacto con usted sobre su registro, seguridad, asuntos legales y otros temas relacionados con el servicio.  Haremos esto con mensajes in-app, notificaciones automatizadas, y/o correo electrónico. Usted no puede optar por no recibir mensajes de servicio de nosotros, incluyendo avisos de seguridad y legales.</p>
      <p className='titulos4'>Análisis y rendimiento </p>
      <p className='titulos3'>La misión de Book of Mormon Central es construir una fe duradera en Jesucristo haciendo que el Libro de Mormón sea accesible, comprensible y defendible para todo el mundo. Queremos que el compromiso con el Libro de Mormón aumente a nivel global y personal. Utilizamos los datos personales de los que disponemos para observar las tendencias sociales, económicas y geográficas en lo que respecta a la enseñanza de las Escrituras y pasajes bíblicos específicos. El análisis de estas tendencias agrega datos sin divulgar información personal identificable. Por ejemplo, sus datos pueden formar parte de las estadísticas sobre el uso general de ScripturePlus en todo el mundo y en países y geografías específicas.</p>
      <p className='titulos3'>Podemos utilizar datos anónimos y agregados de usuarios para promocionar ScripturePlus, destacando indicadores como el número de instalaciones móviles. Podemos utilizar los datos, incluyendo la información personal enviada por el usuario, agregados, datos de uso como el historial de búsqueda, la conclusión del plan de lectura, la actividad de lectura de las Escrituras, etc., los comentarios públicos y la información inferida de estos datos para llevar a cabo investigaciones y desarrollos internos con el fin de mejorar la funcionalidad o la eficiencia de ScripturePlus. A medida que la nueva funcionalidad o contenido del software se ponga en línea, podemos enviar mensajes a los usuarios para informarles sobre las actualizaciones.</p>
      <p className='titulos4'>Encuestas y sondeos</p>
      <p className='titulos3'>Podemos realizar encuestas y sondeos para guiarnos en el desarrollo de nuevas publicaciones de ScripturePlus. Usted no está obligado a participar en nuestras encuestas o sondeos y tendrá opciones sobre la información que elija proporcionar.</p>
      <p className='titulos4'>Cuestiones técnicas y de seguridad</p>
      <p className='titulos3'>Utilizamos datos, que pueden incluir comunicaciones suyas, para investigar, responder y resolver quejas sobre cuestiones legales, de seguridad y técnicas que afectan a ScripturePlus. Podemos utilizar sus datos y comunicaciones si lo consideramos necesario por motivos de seguridad o para investigar posibles fraudes, violaciones de la ley, violaciones de nuestros Términos de uso, violaciones de esta Política de Privacidad o intentos de daño contra otros.</p>
      <p className='titulos4'>Información que recopilamos y cómo la recopilamos</p>
      <p className='titulos3'>No es necesario registrarse para utilizar las funciones limitadas de ScripturePlus. Usted tiene que registrarse para usar las funciones avanzadas de ScripturePlus. El registro nos permite adaptar ScripturePlus para que usted tenga una experiencia más personalizada. Para registrarse, usted nos proporciona su dirección de correo electrónico, la cual revisamos para verificar su fiabilidad enviándole un correo electrónico de confirmación que requiere una respuesta de su parte.</p>
      <p className='titulos3'>En algún momento, es posible que le solicitemos información adicional como su nombre, para poder personalizar los correos electrónicos y otras notificaciones. También podemos proporcionarle la posibilidad de vincular otras credenciales, como sus cuentas de Facebook o Google. Podemos introducir la funcionalidad social de ScripturePlus que depende de que usted nos conceda acceso a sus contactos en su dispositivo móvil.  Si usted elige no darnos acceso, simplemente le impedirá usar ciertas funciones sociales de ScripturePlus, mientras que otras funciones de ScripturePlus que no requieren acceso de contacto continuarán funcionando normalmente. Para poder ofrecer ciertas características sociales, puede ser necesario que ScripturePlus almacene la información recopilada desde su dispositivo móvil en nuestros servidores basados en la nube.</p>
      <p className='titulos3'>Utilizamos datos, que pueden incluir comunicaciones suyas, para investigar, responder y resolver quejas sobre cuestiones legales, de seguridad y técnicas que afectan a ScripturePlus. Podemos utilizar sus datos y comunicaciones si lo consideramos necesario por motivos de seguridad o para investigar posibles fraudes, violaciones de la ley, violaciones de nuestros Términos de uso, violaciones de esta Política de Privacidad o intentos de daño contra otros.</p>
      <p className='titulos4'>Datos confidenciales</p>
      <p className='titulos3'>Al descargar y usar ScripturePlus, no asumimos que tenga una creencia religiosa en particular; simplemente asumimos que está interesado en las Escrituras. No requerimos que los usuarios proporcionen información sobre sus creencias o cualquier otro dato confidencial como raza, etnia u nacionalidad. Si usted elige proporcionar cualquier información confidencial, puede ser usada por Book of Mormon Central para crear una experiencia ScripturePlus más personalizada para usted. Book of Mormon Central solamente procesará los datos confidenciales que usted proporcione para actividades legítimas de enriquecimiento de ScripturePlus en su nombre y no divulgará esta información sin su consentimiento expreso. Mantendremos su información utilizando las medidas de seguridad apropiadas que se abordan en esta política. Usted es libre de hacer preguntas a través del formulario de contacto de Book of Mormon Central https://bookofmormoncentral.es/contact.</p>
      <p className='titulos4'>Niños menores de 16 años</p>
      <p className='titulos3'>No recopilamos información personal de ninguna persona que sepamos que es menor de 16 años sin el consentimiento del padre o tutor legal de ese menor. Un padre o tutor puede consentir el uso de ScripturePlus por un menor, cuyo padre o tutor es el único responsable de supervisar el uso de ScripturePlus por parte del menor y asume toda la responsabilidad por la interpretación y el uso de cualquier información o sugerencia proporcionada a través de ScripturePlus. Si usted cree que podríamos tener alguna información de o acerca de un niño menor de 16 años, por favor contáctenos en https://bookofmormoncentral.es/contact. Si nos enteramos y tenemos confirmación de que hemos recopilado o recibido información personal de un niño menor de 16 años sin verificar el consentimiento de los padres, borraremos esa información.</p>
      <p className='titulos4'>Información de contacto</p>
      <p className='titulos3'>Para hacer preguntas o comentarios sobre esta Política de Privacidad y nuestras prácticas de privacidad, puede ponerse en contacto con nosotros en: Book of Mormon Central, 553 E 100 N, American Fork, UT 84003 o a través de nuestro formulario de contacto en línea: https://bookofmormoncentral.es/contact.</p>

       </div>
 






    </div>
  )
}

export default Politica